// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUxjvcv8CVIM50GuQu4P8JzbRa5whlLxY',
    appId: '1:154220110356:web:9b48987e6ffd66f165fd01',
    messagingSenderId: '154220110356',
    projectId: 'foodapplicationn',
    authDomain: 'foodapplicationn.firebaseapp.com',
    storageBucket: 'foodapplicationn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADZEZBLZwJbnbubM2ys5DpwN5D7IfhPQs',
    appId: '1:154220110356:android:394a28bdfc0ecf4065fd01',
    messagingSenderId: '154220110356',
    projectId: 'foodapplicationn',
    storageBucket: 'foodapplicationn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfV0r0ZARjOAXyzWausIdSNqZ7AmZXdDs',
    appId: '1:154220110356:ios:49063b1f063f019365fd01',
    messagingSenderId: '154220110356',
    projectId: 'foodapplicationn',
    storageBucket: 'foodapplicationn.appspot.com',
    iosClientId: '154220110356-63dvd9dkiitgn9d5mopkbmotfg4cjv9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfV0r0ZARjOAXyzWausIdSNqZ7AmZXdDs',
    appId: '1:154220110356:ios:49063b1f063f019365fd01',
    messagingSenderId: '154220110356',
    projectId: 'foodapplicationn',
    storageBucket: 'foodapplicationn.appspot.com',
    iosClientId: '154220110356-63dvd9dkiitgn9d5mopkbmotfg4cjv9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );
}
