// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8BRZuQl_JpMgZuXI7G1mvsaPYokMvBs',
    appId: '1:397701104668:web:63246d279aec67af1fcbd9',
    messagingSenderId: '397701104668',
    projectId: 'backendfood',
    authDomain: 'backendfood.firebaseapp.com',
    storageBucket: 'backendfood.appspot.com',
    measurementId: 'G-MC82E0ZKR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjbKTC_NmlCDG6G1tBdJ1zEDVqHKJyczQ',
    appId: '1:397701104668:android:8e3b495346f8a7f21fcbd9',
    messagingSenderId: '397701104668',
    projectId: 'backendfood',
    storageBucket: 'backendfood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvKYlPfI04O4AwbmGR7zuzvyBAmUMYbbs',
    appId: '1:397701104668:ios:65874fac6be29c121fcbd9',
    messagingSenderId: '397701104668',
    projectId: 'backendfood',
    storageBucket: 'backendfood.appspot.com',
    iosClientId: '397701104668-q0m78olg3hdb66ft2ef89l7kul29h8iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvKYlPfI04O4AwbmGR7zuzvyBAmUMYbbs',
    appId: '1:397701104668:ios:65874fac6be29c121fcbd9',
    messagingSenderId: '397701104668',
    projectId: 'backendfood',
    storageBucket: 'backendfood.appspot.com',
    iosClientId: '397701104668-q0m78olg3hdb66ft2ef89l7kul29h8iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );
}
